// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWjrmbHDNQ_0DJn3L4vsw24jnZC8PX-qw',
    appId: '1:450377667712:web:07d381177700ab3cfc4265',
    messagingSenderId: '450377667712',
    projectId: 'midhackathon-83656',
    authDomain: 'midhackathon-83656.firebaseapp.com',
    storageBucket: 'midhackathon-83656.appspot.com',
    measurementId: 'G-PX5MZ7KJFL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXQ7LJx2QSQJrh7Izqx2H1m3MO63r1ms0',
    appId: '1:450377667712:android:63eb949abf7597d9fc4265',
    messagingSenderId: '450377667712',
    projectId: 'midhackathon-83656',
    storageBucket: 'midhackathon-83656.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDtDwY1H1gIW6F_bdIPChy148jTWm25Nc',
    appId: '1:450377667712:ios:bc2c6677a36fcb1cfc4265',
    messagingSenderId: '450377667712',
    projectId: 'midhackathon-83656',
    storageBucket: 'midhackathon-83656.appspot.com',
    iosBundleId: 'com.example.mid',
  );
}
